tag-template: 'release/v$NEXT_MAJOR_VERSION'
version-template: '$MAJOR'
prerelease: true
categories:
  - title: '🐛 Bugs'
    labels: ['bug']
  - title: '✨ Enhancements'
    labels: ['enhancement']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What’s Changed

  $CHANGES
