name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate build number"
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
      - name: "Create draft release"
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "release-drafter.yml"
          name: "v$NEXT_MAJOR_VERSION  - Build ${{ steps.buildnumber.outputs.build_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Delete old artifacts"
        run: curl -X DELETE ${{ steps.draft_release.outputs.upload_url }}
      - name: "Checkout project"
        uses: actions/checkout@v2
      - name: "🧰 Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build + sign app"
        run: |
          ./gradlew :app:assembleDebug --stacktrace
        shell: bash
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: "☁ Upload apk to GitHub"
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: "Zip build artifact"
        run: zip app-artifacts.zip app/build/outputs/apk/debug/app-debug.apk
      - name: "Upload artifact to draft release"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./app-artifacts.zip
          asset_name: app-artifacts.zip
          asset_content_type: application/zip
