name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Create draft release"
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "release-drafter.yml"
          name: "v$NEXT_MAJOR_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
